POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Michelle Cordeiro",
  "email": "zxzx@gmail.com"
}

###

GET http://localhost:3333/invites/mic_cord

###
GET http://localhost:3333/subscribers/mic_cord/ranking/clicks
