POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Usuário Indicado 3",
  "email": "indicado3@gmail.com",
  "referrer": "c1a0ec68-9856-480b-850e-0053b67cb8b2"
}

###

# GET http://localhost:3333/invites/37a5a8b7-cdbc-436b-9703-08dbc9f255ce

GET http://localhost:3333/invites/c1a0ec68-9856-480b-850e-0053b67cb8b2


### CLICKS NO LINK
# GET http://localhost:3333/subscribers/37a5a8b7-cdbc-436b-9703-08dbc9f255ce/ranking/clicks

GET http://localhost:3333/subscribers/c1a0ec68-9856-480b-850e-0053b67cb8b2/ranking/clicks


### INDICAÇÕES
GET http://localhost:3333/subscribers/37a5a8b7-cdbc-436b-9703-08dbc9f255ce/ranking/count

# GET http://localhost:3333/subscribers/c1a0ec68-9856-480b-850e-0053b67cb8b2/ranking/count

### POSIÇÃO
GET http://localhost:3333/subscribers/37a5a8b7-cdbc-436b-9703-08dbc9f255ce/ranking/position


### GET RANKING
GET http://localhost:3333/ranking
